### PR TITLE
Refactoring/UI

### PR DESCRIPTION
**Pull request by Zadvornyi**
Refactoring kraken_web_interface. Move some functions to utils

### CODE REVIEW

**Comment by krakenrf** [comment]
Can you check what might be causing this error:

Traceback (most recent call last):
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_UI/_web_interface/kraken_web_interface.py", line 34, in <module>
    from variables import (
ImportError: cannot import name 'dsp_settings' from 'variables' (/home/krakenrf/krakensdr_doa/krakensdr_doa/_UI/_web_interface/variables.py)

**Comment by Zadvornyi** [comment]
Yes of course, I will check

**Comment by Zadvornyi** [comment]
Please check, I have resolved merge conflicts

**Comment by godsic** [comment]
@Zadvornyi The PR overrides changes introduced in #85, notably default `dsp_settings` and polling interval of `settings_change_watcher`.  Could you please double check that PR does not change functionality?

**Comment by Zadvornyi** [comment]
I have changed 
Screenshot 2023-07-19 at 13 24 15

**Comment by godsic** [comment]
@krakenrf Checked, no apparent regressions.
